  name: Windows workflow

  on:
    push:
      branches:
        - develop
    pull_request:
      branches:
        - develop

  jobs:
    prepare:
      runs-on: [self-hosted, windows]
      steps:
        - 
          name: Clean workspace
          run: |
            echo "Cleaning up previous run"
            Remove-Item -LiteralPath "${{ github.workspace }}/libcore-build" -Force -Recurse
    build:
      needs: prepare
      runs-on: [self-hosted, windows]
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            path: libcore
            clean: true
            submodules: true

        - name: Build libcore
          run: |
            mkdir libcore-build
            cd libcore-build
            cmake  -DBUILD_TESTS=ON ../libcore
            cmake --build . --config Debug -- /m:1